dist: bionic

env:
  global:
    - HADOOP_VERSION=3.3.1
    - IMAGE_TAG=crossflowai/hadoop:${HADOOP_VERSION}
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=${TRAVIS_CPU_ARCH}] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - docker buildx version
  - docker buildx create --use
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

script:
#  - if [ "${TRAVIS_CPU_ARCH}" = "amd64" ]; then docker buildx build --platform linux/amd64 -t ${IMAGE_TAG} -f Dockerfile . ; else docker buildx build --platform linux/arm64 -t ${IMAGE_TAG} -f Dockerfile . ; fi
  - docker buildx build --platform linux/amd64 -t ${IMAGE_TAG} -f dockerfile . 
#  - docker build -t ${IMAGE_TAG} -f Dockerfile . 
#  - docker push ${IMAGE_TAG}
